[package]
name = "ca-web-server"
version = "0.1.0"
authors = ["maron8676 <maron8676@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
